name: Basic Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test step 1
      run: echo "Step 1 works"
    
    - name: Test step 2
      run: echo "Step 2 works"
    
    - name: Test step 3
      run: echo "Step 3 works"