name: Test Permissions Simple

on:
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  projects: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Test project access
      uses: actions/github-script@v7
      with:
        script: |
          console.log('Testing project access...');
          
          const projectQuery = `
            query {
              user(login: "jreakin") {
                projectsV2(first: 10) {
                  nodes {
                    id
                    title
                    number
                  }
                }
              }
            }
          `;
          
          try {
            const result = await github.graphql(projectQuery);
            console.log('Projects found:', result.user.projectsV2.nodes.length);
            console.log('Project titles:', result.user.projectsV2.nodes.map(p => p.title));
          } catch (error) {
            console.log('Error accessing projects:', error.message);
            if (error.errors) {
              console.log('GraphQL errors:', JSON.stringify(error.errors, null, 2));
            }
          }