name: Test GitHub CLI

on:
  workflow_dispatch:

permissions:
  issues: read
  projects: read

jobs:
  test-gh:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install GitHub CLI
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh -y

    - name: Authenticate
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Test basic commands
      run: |
        echo "GitHub CLI version:"
        gh --version
        
        echo "Authentication status:"
        gh auth status
        
        echo "Repository info:"
        gh repo view --json name,owner
        
        echo "Project info:"
        gh project view 4 --owner jreakin
        
        echo "✅ GitHub CLI test completed successfully!"