name: Test Automation

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  test-comment:
    runs-on: ubuntu-latest
    
    steps:
    - name: Add test comment
      uses: actions/github-script@v7
      with:
        script: |
          const { issue } = context.payload;
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue.number,
            body: `🧪 **Test Comment**: This is a test of the simplified workflow. Label: ${context.payload.label.name}`
          });
          
          console.log(`Added test comment to issue #${issue.number}`);