name: Test Permissions

on:
  workflow_dispatch:

permissions:
  issues: read
  projects: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Test basic commands
      run: |
        echo "Testing basic commands..."
        echo "Repository: ${{ github.repository }}"
        echo "Token available: ${{ secrets.GITHUB_TOKEN != '' }}"
        echo "Basic test successful!"

    - name: Test API access
      run: |
        echo "Testing GitHub API access..."
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}
        echo "API access successful!"